spring:
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/xyz?useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-lifetime: 30000
    connection-timeout: 10000
    # https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  jpa:
    show-sql: true
    open-in-view: false
    # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-access.jpa-properties
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          check_nullability: true

# Register P6LogFactory to log JDBC events
decorator.datasource.p6spy.enable-logging: true
# Use logging for default listeners [slf4j, sysout, file, custom]
decorator.datasource.p6spy.logging: slf4j
# Custom log format, if specified com.p6spy.engine.spy.appender.CustomLineFormat will be used with this log format
# https://github.com/p6spy/p6spy/blob/master/src/main/java/com/p6spy/engine/spy/appender/MultiLineFormat.java
decorator.datasource.p6spy.log-format: 'took %(executionTime)ms | %(category) | connection %(connectionId) | %(sqlSingleLine)'
# Report the effective sql string (with '?' replaced with real values) to tracing systems.
# NOTE this setting does not affect the logging message.
decorator.datasource.p6spy.tracing.include-parameter-values: true
